version: '3.9'
services:
  db:
    image: arangodb:latest
    environment:
      ARANGO_ROOT_PASSWORD: ${VITE_DB_PASSWORD:-root}
    ports:
      - ${VITE_DB_PORT:-8529}:8529
    volumes:
      - arangodb_data_container:/var/lib/arangodb3
      - arangodb_apps_data_container:/var/lib/arangodb3-apps

volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
